version: '3.8'

services:
  go-rpc-server:
    build:
      context: .
      target: server
    ports:
      - "50051:50051"
      - "8080:8080"
    depends_on:
      - redis
    command: ["/go-rpc-server", "-network", "tcp", "-grpc-port", "50051", "-host", "127.0.0.1", "-gateway-port", "8080"]
    volumes:
      - ./internal/proto/file_service.swagger.json:/app/file_service.swagger.json

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /app/file_service.swagger.json
    volumes:
      - ./internal/proto/file_service.swagger.json:/app/file_service.swagger.json
    depends_on:
      - go-rpc-server

volumes:
  redis-data:
