version: '3.8'

services:
  go-rpc-server:
    build:
      context: .
      target: server
    ports:
      - "50051:50051"
    depends_on:
      - redis
    command: ["/go-rpc-server", "-network", "tcp", "-grpc-port", "50051"]

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  docserver:
    build:
      context: .
      target: docserver
    ports:
      - "8080:8080"
    command: ["/doc-server", "-port-doc", "8080"]
    volumes:
      - ./doc:/doc  

volumes:
  redis-data:
