name: CI

on:
  push:
    branches:
      - main
      - master
      - '**/*.go'
  pull_request:
    branches:
      - main
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod download

      - name: Run golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run

      - name: Run unit tests
        run: go test -v ./... --exclude=./integration_tests/...

  integration_tests:
    runs-on: ubuntu-latest
    needs: lint_and_test

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod download

      - name: Run integration tests
        run: go test -v ./integration_tests/...
